= TR-DOS _Disassembled_
:author: Marcos Cruz (programandala.net)
:revdate: 2017-02-12

:period: .
:char94: ^

// Last modified: 201702120142

// This file is written in AsciDoc/Asciidoctor format
// (see <http://asciidoctor.org>).

== Description

The goal of this project is to disassemble TR-DOS 5.03, in order to
study it and fix some problems found during the development of its
support for http://programandala.net/en.program.solo_forth.html[Solo
Forth] (http://github.com/programandala-net/solo-forth[Solo Forth in
GitHub]).

== Directories and files

....
.
├── inc                                    = ZX Spectrum symbols for the disassembler
│   ├── zx_spectrum_char_codes.z80s
│   ├── zx_spectrum_rom_routines.z80s
│   ├── zx_spectrum_system_variables.z80s
│   ├── zx_spectrum_trdos_addresses.z80s
│   └── zx_spectrum_trdos_codes.z80s
├── Makefile
├── README.adoc                            = This file
├── TO-DO.adoc                             = To-Do list
├── tools                                  = programs used by Makefile or during the development
│   ├── make_blocks.c_commands_table.fs
│   ├── make_blocks.rst_20.fs
│   └── tidier.vim                         = VimL program that postprocess the disassembly
├── trdos.blocks.txt                       = Block definitions for the disassembler
├── trdos.raw.z80s                         = Disassembly created by the disassembler
├── trdos.reassembled.rom                  = TR-DOS reassembled from <trdos.z80s>
├── trdos.rom                              = Original ROM of TR-DOS 5.03 to be disassembled
├── trdos.symbols.input.z80s               = Symbols defined for the disassembler
├── trdos.symbols.output.z80s              = Output symbols of the disassembly
└── trdos.z80s                             = Final disassembly, postprocessed by <tools/tidier.vim>
....

== Requirements

In order to <<_how_to_disassemble,disassemble the ROM>>, the following
programs must be installed:

- https://www.tablix.org/~avian/z80dasm/[z80dasm], by Tomaž Šolc.
- http://vim.org[Vim], by Bram Moolenaar

The following programs are needed to reassemble the disassembly, what
is optional:

- http://pasmo.speccy.org[Pasmo], by Julián Albo
- http://www.gnu.org/software/diffutils/[diffutils], by Paul Eggert,
  Mike Haertel, David Hayes, Richard Stallman, and Len Tower.

== How to disassemble

1. Make sure the <<_requirements,required programs>> are installed.
2. Enter the project directory and give the `make` command.
3. If you want to assemble the disassembly and check that the result
   is identical to the original ROM, give the `make back` command.

== Bibliography

Documentation used for this project, listed in order of publication:

- _Technology Research Beta 128 Disk Interface — User Manual_, 1986.
  http://www.worldofspectrum.org/documentation.html#manuals,
  http://www.worldofspectrum.org/pub/sinclair/hardware-info/Beta128DiskInterface_Manual.txt.

- _TR-DOS для профессионалов и любителей_ (_TR-DOS for professionals
  and amateurs_), by Yu Pomortsev, 1994. PDF version by Deny
  (Denisenko DA), 2007. http://vtrdos.ru,
  http://trd.speccy.cz/book/TRDOSUA.ZIP.

- _Описание и полный дизассемблер ПЗУ TR-DOS 5.04T_ (Description and
  full disassembly of TR-DOS 5.04T), by Павел Федин (Paul Fedin),
  1996{period}  http://vtrdos.ru,
  http://trd.speccy.cz/book/TRDISASM.ZIP.

- _TR-DOS System Functions_, by Igor Yudincev, 1997-06-01.
  http://ramsoft.bbk.org.omegahg.com/tech/tr-info.zip.

- _Work in TR-DOS from command line and from BASIC_, by Igor Yudincev,
  1997-06-27.  http://ramsoft.bbk.org.omegahg.com/tech/tr-info.zip.

- _TR-DOS disk specs_, anonymous, 1997-09-28.
  http://ramsoft.bbk.org.omegahg.com/tech/tr-info.zip.

- _Russian Most Popular Spectrum Models (combined) FAQ and TECH INFO_,
  by Potapov Vsevolod Viktorovich, 1997-10-25.
  http://www.worldofspectrum.org/rusfaq/

- TR-DOS v5.xx - programmer's manual_, by Andrew MOA and Mac
  Buster{char94}Extreme, 1990 (English translation, 1999),
  http://www.worldofspectrum.org/documentation.html#manuals,
  http://www.worldofspectrum.org/pub/sinclair/hardware-info/TR-DOS_Programming.txt.

- _TR-DOS v5.xx variables in Beta 128 Disk interface_, by Mac
  Buster{char94}Extreme, 2000.
  http://www.worldofspectrum.org/documentation.html#manuals,
  http://www.worldofspectrum.org/pub/sinclair/hardware-info/TR-DOS_Variables.txt.

Websites that were used:

- http://vtrdos.ru
- http://tr-dos.ru

== History

The project started on 2016-08-14.

